[tool.black]
line-length = 100
target-version = ["py311"]
exclude = '''
/(
    \.venv
  | build
  | dist
  | htmlcov
)/
'''

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["naver_cafe_scraper"]
skip = [".venv", "build", "dist", "htmlcov"]

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203"]
exclude = [".venv", "build", "dist", "htmlcov"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-q --cov=naver_cafe_scraper --cov-report=term-missing"
testpaths = ["tests"]

[tool.coverage.run]
branch = true
source = ["naver_cafe_scraper"]

[tool.coverage.report]
show_missing = true
skip_covered = false
